api-version: "1.20" # TODO change to 1.21 once stable
authors: [ "lokka30" ]
description: "Security solution for Minecraft servers and proxies"
main: "io.github.arcaneplugins.blackwidow.plugin.bukkit.BlackWidow"
name: "BlackWidow"
website: "https://github.com/ArcanePlugins/BlackWidow/"
version: "${project.version}"
perissions:
  blackwidow.*:
    default: op
    description: "All BlackWidow permissions (admin/operator use)"
    children:
      blackwidow.command.*: true
  blackwidow.command.*:
    default: true
    description: "Access to all BlackWidow commands"
    children:
      blackwidow.command.bw.*: true
  blackwidow.command.bw:
    default: true
    description: "Access to the base `/bw` command"
  blackwidow.command.bw.*:
    default: op
    description: "Access to all `/bw` subcommands"
    children:
      blackwidow.command.bw: true
      blackwidow.command.bw.reload: true
      blackwidow.command.bw.version: true
  blackwidow.command.bw.reload:
    default: op
    description: "Access to `/bw reload`"
  blackwidow.command.bw.version:
    default: true
    description: "Access to `/bw version`"
