cmd-blocking:
  chains:
    - id: "stop-plugin-snooping"
      enabled: true
      policy: "DENY"
      regex: false
      rules:
        - "/pl"
        - "/plugins"
        - "/ver"
        - "/version"
        - "/about"
        - "/icanhasbukkit"
        - "/?"
        - "/help"
        - "/ehelp"
        - "/spigot"
        - "/paper"
      actions:
        - id: "send-message"
          msg:
            - "%prefix% You can't run that command."
  default-behaviour:
    policy: "ALLOW"
    actions: [ ]
  deny-colon-in-first-arg:
    enabled: true
    actions:
      - id: "send-message"
        msg:
          - "%prefix% You can''t use the colon character ':' in the first part of your
        commands."
  filtering:
    execution: true
    suggestion: true
  operators-bypass-completely: true
do-not-touch:
  version:
    context: ""
    original: 1
    installed: 1
